AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Event-Driven Serverless Application
  API Gateway -> Ingestion Lambda -> SQS -> Processing Lambda -> DynamoDB

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment stage

  LogLevel:
    Type: String
    Default: INFO
    AllowedValues:
      - DEBUG
      - INFO
      - WARNING
      - ERROR
    Description: Lambda log level

  MessageRetentionPeriod:
    Type: Number
    Default: 345600
    Description: SQS message retention period in seconds (default 4 days)

  MaxReceiveCount:
    Type: Number
    Default: 3
    Description: Maximum number of receive attempts before sending to DLQ

Globals:
  Function:
    Runtime: python3.11
    Timeout: 30
    MemorySize: 256
    Tracing: Active
    Environment:
      Variables:
        LOG_LEVEL: !Ref LogLevel
        POWERTOOLS_SERVICE_NAME: event-driven-app

Resources:
  # ---------- API Gateway ----------
  EventApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${Stage}-event-api"
      StageName: !Ref Stage
      TracingEnabled: true
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          ThrottlingBurstLimit: 100
          ThrottlingRateLimit: 50
          LoggingLevel: INFO
      AccessLogSetting:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: >-
          {"requestId":"$context.requestId",
          "ip":"$context.identity.sourceIp",
          "requestTime":"$context.requestTime",
          "httpMethod":"$context.httpMethod",
          "resourcePath":"$context.resourcePath",
          "status":"$context.status",
          "responseLatency":"$context.responseLatency"}

  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/apigateway/${Stage}-event-api"
      RetentionInDays: 30

  # ---------- Ingestion Function ----------
  IngestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-event-ingestion"
      Description: Validates incoming event payloads and publishes to SQS
      Handler: app.lambda_handler
      CodeUri: src/ingestion_function/
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref EventQueue
      Policies:
        - Statement:
            - Sid: AllowSQSSendMessage
              Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt EventQueue.Arn
      Events:
        PostEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EventApi
            Path: /events
            Method: POST
      ReservedConcurrentExecutions: 50

  IngestionFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Stage}-event-ingestion"
      RetentionInDays: 14

  # ---------- SQS Queue ----------
  EventQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Stage}-event-queue"
      VisibilityTimeout: 180
      MessageRetentionPeriod: !Ref MessageRetentionPeriod
      KmsMasterKeyId: alias/aws/sqs
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt EventDeadLetterQueue.Arn
        maxReceiveCount: !Ref MaxReceiveCount

  EventQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref EventQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowIngestionFunctionOnly
            Effect: Allow
            Principal:
              AWS: !GetAtt IngestionFunctionRole.Arn
            Action:
              - sqs:SendMessage
            Resource: !GetAtt EventQueue.Arn

  # ---------- Dead Letter Queue ----------
  EventDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Stage}-event-dlq"
      MessageRetentionPeriod: 1209600
      KmsMasterKeyId: alias/aws/sqs

  # ---------- Processing Function ----------
  ProcessingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-event-processing"
      Description: Processes SQS messages and writes records to DynamoDB
      Handler: app.lambda_handler
      CodeUri: src/processing_function/
      Timeout: 60
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref EventTable
      Policies:
        - Statement:
            - Sid: AllowDynamoDBWriteRead
              Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:UpdateItem
              Resource: !GetAtt EventTable.Arn
        - Statement:
            - Sid: AllowSQSConsume
              Effect: Allow
              Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
              Resource: !GetAtt EventQueue.Arn
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt EventQueue.Arn
            BatchSize: 10
            MaximumBatchingWindowInSeconds: 5
            FunctionResponseTypes:
              - ReportBatchItemFailures
      ReservedConcurrentExecutions: 25

  ProcessingFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Stage}-event-processing"
      RetentionInDays: 14

  # ---------- DynamoDB Table ----------
  EventTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Stage}-events"
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      AttributeDefinitions:
        - AttributeName: event_id
          AttributeType: S
        - AttributeName: source
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: event_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: source-created_at-index
          KeySchema:
            - AttributeName: source
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # ---------- CloudWatch Alarms ----------
  DLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${Stage}-event-dlq-messages"
      AlarmDescription: Alarm when messages appear in the dead-letter queue
      Namespace: AWS/SQS
      MetricName: ApproximateNumberOfMessagesVisible
      Dimensions:
        - Name: QueueName
          Value: !GetAtt EventDeadLetterQueue.QueueName
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold

  IngestionErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${Stage}-ingestion-errors"
      AlarmDescription: Alarm when the ingestion function has errors
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref IngestionFunction
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanOrEqualToThreshold

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${EventApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/events"

  EventQueueUrl:
    Description: SQS Queue URL
    Value: !Ref EventQueue

  EventQueueArn:
    Description: SQS Queue ARN
    Value: !GetAtt EventQueue.Arn

  DeadLetterQueueUrl:
    Description: Dead-Letter Queue URL
    Value: !Ref EventDeadLetterQueue

  DynamoDBTableName:
    Description: DynamoDB Table Name
    Value: !Ref EventTable

  IngestionFunctionArn:
    Description: Ingestion Lambda Function ARN
    Value: !GetAtt IngestionFunction.Arn

  ProcessingFunctionArn:
    Description: Processing Lambda Function ARN
    Value: !GetAtt ProcessingFunction.Arn
